module.exports = {
  wifeName: 'Fulan1',
  wifeFullName: 'Fulan1',
  wifeFullNameCaption: 'Anak pertama dari Bapak Fulan11 & Ibu Fulan12',
  wifeFamily1: 'Fulan11',
  wifeFamily2: 'Fulan12',
  husbandName: 'Fulan2',
  husbandFullName: 'Fulan2',
  husbandFullNameCaption: 'Anak pertama dari Bapak Fulan21 & Ibu Fulan22',
  husbandFamily1: 'Fulan21',
  husbandFamily2: 'Fulan22',
  day: 'Ahad',
  date: '1 Januari 2000',
  address1: 'Jl. Leaky Cauldron No. 0 ',
  address2: 'Archenland',
  address3: 'Shire, Middleearth',
  address4: 'Neverland',
  address5: 'Narnia',
  addressLocation: 'https://goo.gl/maps/hcyz9W2YkL3FdDoA8',
}
